name: Contact - Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    # dotnet build and publish
    - name: Instal dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish
      run: |
        dotnet publish -c Release -o 4oito6.Contact.Api 
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: contact-test # Replace with your app name
        publish-profile: ${{secrets.contact_publishprofile}} # secret variable
        package: './4oito6.Contact.Api' #todo change this
