name: .NET Core

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore 4oito6
    - name: Build
      run: dotnet build 4oito6 --configuration Release --no-restore
    - name: Test
      run: dotnet test 4oito6 --no-restore --verbosity normal
